### ISSUE TITLE
Joshie QA

### ISSUE THREAD

**Issue by joshiefishbein** [sanctuarycomputer/contentful-fragment-homepage#1]
Desktop:
1. **For the App preview frame, make the box-shadow gradient poles both rgba() values with .25 for transparency**. It comes off pretty harsh right now, and the alpha layer will help with the shadow's transition from the blue to white background.
2. Decrease padding on buttons in hero just a little bit in both directions, the design show them wrapping inner text a bit more tightly.

Responsive:
- There's a weird moment between 824px and 1024px viewport width where the app frame disappears but the text in the hero stays anchored to the left. Can this breakpoint fully adopt the mobile layout?

Mobile:
1. Contentful logo and "By Sanctu Compu" crash into each other on mobile. Maybe we decrease the size of both?
2. Too much space above the hero title and the logo bar.
3. Is there a way we can add the app frame back below the hero buttons and transitioning into the white body background the same way?
4. There's a large gap above and a below the body content, can we halve that whitespace?

General design thoughts:
1. Can we add a "Get Started" button or link at the bottom of the body content? There should never be a page on the web without recirculation at the end of the page.
2. Can we double check the contrast ratio of the "Start Building Free" button meets Level AA compliance? The blue seems a bit too light.
3. When I'm tabbing through the page, the third focus puts me in the "Global Settings" field in the app frame haha. Should this happen?
4. Contentful logo should link to Contentful, Sanctuary Computer should link to Sanctuary Computer

**Comment by danhemerlein** [comment]
Thanks very much for these notes Joshie.  The master branch should now have fixes for everything here expect for: 

Mobile #3 - based on my conversations with Hugh, I thiiink we want the app frame to be completely hidden on mobile because this site is closely imitating the design/layout of the actual Contentful site

General Design #3 - Yup! the "Global Settings" field is an input so that is the expected behavior.
